<!--
  ~ Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~
  ~ WSO2 Inc. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<!DOCTYPE assembly [
        <!ELEMENT assembly (id|formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode|filtered)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes)*>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|filtered|destName)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        ]>
<assembly>
    <id>bin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>

    <fileSets>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/README*</exclude>
                <exclude>**/LICENSE*</exclude>
                <exclude>**/INSTALL*</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/axis2services/sample01.aar</exclude>
                <exclude>**/axis2services/echo/**</exclude>
                <exclude>**/axis2services/version/**</exclude>
                <exclude>**/pom.xml</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/master-datasources.xml</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/registry.xml</exclude>
                <exclude>**/client-truststore.jks</exclude>
                <exclude>**/wso2carbon.jks</exclude>
                <exclude>**/WSO2AM_DB.h2.db</exclude>
                <exclude>**/WSO2DM_DB.h2.db</exclude>
                <exclude>**/conf/axis2/axis2_client.xml</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/etc/launch.ini</exclude>
                <exclude>**/lib/httpmime*</exclude>
                <exclude>**/lib/encoder*</exclude>
                <exclude>**/plugins/jaxb*</exclude>
                <exclude>**/security/authenticators.xml</exclude>

                <exclude>**/plugins/org.wso2.carbon.localentry.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.security.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.library.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.task.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.sequences.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.proxyadmin.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.priority.executors.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.message.store.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.message.processor.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.templates.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.artifactuploader.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.endpoint.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.inbound.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.rest.api.ui*</exclude>
            </excludes>
        </fileSet>

        <!-- Copying Runtimes-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/lib/runtimes
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/lib/runtimes/</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <includes>
                <include>**/*.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

        <!-- Multi-tenancy related file -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/multitenancy
            </outputDirectory>
            <includes>
                <include>**/stratos.xml</include>
                <include>**/multitenancy-packages.xml</include>
                <include>**/usage-throttling-agent-config.xml</include>
                <include>**/cloud-services-desc.xml</include>
            </includes>
            <filtered>true</filtered>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf</outputDirectory>
            <includes>
                <include>**/tenant-mgt.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/resources/styles/css</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/admin
            </outputDirectory>
            <includes>
                <include>**/**.css</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/resources/styles/images</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/images
            </outputDirectory>
            <includes>
                <include>**/**.gif</include>
                <include>**/**.png</include>
            </includes>
        </fileSet>

        <!-- Copy Documentation -->
        <fileSet>
            <directory>target/site</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/docs</outputDirectory>
            <fileMode>755</fileMode>
        </fileSet>

        <!-- Copy the landing page webapp -->
        <!-- <fileSet>
             <directory>src/repository/resources/stratos_root</directory>
             <outputDirectory>wso2cdm-${pom.version}/repository/deployment/server/webapps/STRATOS_ROOT</outputDirectory>
             <fileMode>755</fileMode>
         </fileSet>-->
        <!--Removed -->
        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/modules
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/</outputDirectory>
            <includes>
                <include>**/carbon/</include>
                <include>**/jaggery-test/</include>
                <include>**/process/</include>
                <include>**/uuid/</include>
                <include>**/i18n/</include>
                <include>**/ws/</include>
                <include>**/appmgtpublisher/</include>
                <include>**/lifecycle/</include>
                <include>**/utils/</include>
                <include>**/caramel/</include>
                <include>**/markdown/</include>
                <include>**/handlebars/</include>
                <include>**/event/</include>
                <include>**/claims/</include>
                <include>**/permission/</include>
                <include>**/registration/</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/conf</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf</outputDirectory>
            <includes>
                <include>**/identity.xml</include>
                <include>**/api-manager.xml</include>
                <include>**/sso-idp-config.xml</include>
                <include>**/application-authentication.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/security
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/security
            </outputDirectory>
            <includes>
                <include>**/sso-sp-config.properties</include>
                <include>**/entitlement.properties</include>
                <include>**/trusted-idp-config.xml</include>
                <include>**/cipher-text.properties</include>
                <include>**/cipher-tool.properties</include>
            </includes>
            <excludes>
                <exclude>authenticators.xml</exclude>
            </excludes>
        </fileSet>

        <!-- <fileSet>
             <directory>
                 src/repository/conf/identity/
             </directory>
             <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/identity/</outputDirectory>
             <includes>
                 <include>**/**</include>
             </includes>
         </fileSet>-->
        <fileSet>
            <directory>src/repository/conf/datasources</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/datasources
            </outputDirectory>
            <includes>
                <include>**/master-datasources.xml</include>
                <include>**/cdm-datasources.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/resources</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!--data-bridge configuration-->
        <fileSet>
            <directory>src/repository/conf/data-bridge</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/data-bridge
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/service-provider
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/service-provider</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying identity related dbscripts -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/identity
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/identity</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying API management related dbscripts -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/apimgt
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/apimgt</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!--Copying modules-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/modules
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/modules/encode</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/encode</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/modules/sso</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/sso</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying Device Management related dbscripts -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/cdm
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/cdm</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/resources
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources
            </outputDirectory>
        </fileSet>


        <!-- Copying Mobile plugin management related dbscripts -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.mobile.device.mgt.version}/dbscripts/cdm/plugins
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/cdm/plugins
            </outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying Authentication Endpoint webapp -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/webapps
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps
            </outputDirectory>
            <includes>
                <include>authenticationendpoint.war</include>
                <include>oauth2.war</include>
                <include>dynamic-client-web.war</include>
            </includes>
        </fileSet>
        <!--copy jaxrs web app for OAuth feature-->


        <!-- Copying mdm app extensions -->
        <fileSet>
            <directory>../apps/jaggery/mdm/src/mdm/</directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/mdm
            </outputDirectory>
        </fileSet>

        <!-- Copying mdm app from devicemgt app-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/uuf-app/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/devicemgt
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/devicemgt/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/devicemgt
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/webapps/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps/
            </outputDirectory>
            <excludes>
                <exclude>appmoauth2.war</exclude>
            </excludes>
            <filtered>false</filtered>
            <fileMode>644</fileMode>
        </fileSet>

        <!-- Copying API Manager Publisher and Store Jaggery apps -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/publisher/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/publisher
            </outputDirectory>
            <excludes>
                <exclude>publisherLogo/**</exclude>
                <exclude>publisherTheme/**</exclude>
                <exclude>publisherSite/**</exclude>
                <exclude>footer/**</exclude>
                <exclude>localstyles.css</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/store/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/store
            </outputDirectory>
            <excludes>
                <exclude>storeLogo/**</exclude>
                <exclude>storeSite/**</exclude>
                <exclude>base-page/**</exclude>
                <exclude>login/**</exclude>
                <exclude>styles-layout.css</exclude>
            </excludes>
        </fileSet>

        <!-- Copying synapse-config directory -->
        <fileSet>
            <directory>src/repository/resources</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server
            </outputDirectory>
            <excludes>
                <exclude>**/empty.txt</exclude>
                <exclude>**/styles/**</exclude>
            </excludes>
        </fileSet>

        <!-- Copying RXTs corresponding API management related components -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/rxts
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources/rxts
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/identity
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/identity
            </outputDirectory>
            <includes>
                <include>**/sso-idp-config.xml</include>
                <include>**/saml1-assertion-config</include>
                <include>**/msg-mgt.properties</include>
                <include>**/entitlement.properties</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/identity/identity-providers
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/conf/identity/identity-providers
            </outputDirectory>
            <includes>
                <include>**/default.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/identity/service-providers
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/conf/identity/service-providers
            </outputDirectory>
            <includes>
                <include>**/default.xml</include>
            </includes>
        </fileSet>

        <!-- Analytics related config -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/analytics/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/analytics</outputDirectory>
            <includes>
                <include>**/analytics-config.xml</include>
                <include>**/rdbms-config.xml</include>
                <!--<include>**/hbase-analytics-config.xml</include>-->
                <include>**/analytics-data-config.xml</include>
                <include>**/analytics-eventsink-config.xml</include>
            </includes>
        </fileSet>
    </fileSets>



    <dependencySets>
        <dependencySet>
            <outputDirectory>${pom.artifactId}-${pom.version}/lib/endorsed</outputDirectory>
            <includes>
                <include>javax.el:el-api:jar</include>
            </includes>
        </dependencySet>
        <dependencySet>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/client/modules
            </outputDirectory>
            <includes>
                <include>org.hibernate.wso2:hibernate:jar</include>
                <include>org.apache.rampart:rampart:mar</include>
            </includes>
        </dependencySet>
    </dependencySets>

    <files>
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/webapps/mdm-android-agent.war
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps
            </outputDirectory>
            <fileMode>755</fileMode>
        </file>
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/webapps/mdm-windows-agent.war
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps
            </outputDirectory>
            <fileMode>755</fileMode>
        </file>
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/webapps/mdm-admin.war
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps
            </outputDirectory>
            <destName>devicemgt_admin.war</destName>
        </file>
        <file>
            <source>
                ../tools/mdm-android-agent-archetype/target/mdm-android-agent-archetype-${mdm.android.agent.archetype.version}.jar
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/tools
            </outputDirectory>
            <fileMode>755</fileMode>
        </file>
        <file>
            <source>../tools/mdm-android-agent-archetype/README.txt</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/tools
            </outputDirectory>
            <fileMode>755</fileMode>
        </file>
        <file>
            <source>../tools/mdm-android-agent-archetype/android-agent.sh</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/tools
            </outputDirectory>
            <fileMode>755</fileMode>
        </file>
        <!-- Copying synapse.properties file -->
        <file>
            <source>src/repository/conf/synapse.properties</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf</outputDirectory>
            <destName>synapse.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <!-- Copying synapse-handlers.xml file -->
        <file>
            <source>src/repository/conf/synapse-handlers.xml</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf</outputDirectory>
            <destName>synapse-handlers.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <!-- <file>
             <source>
                 ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/tomcat/webapp-classloading.xml
             </source>
             <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/tomcat</outputDirectory>
             <filtered>true</filtered>
             <fileMode>644</fileMode>
         </file>
         <file>
             <source>
                 ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/tomcat/webapp-classloading-environments.xml
             </source>
             <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/tomcat</outputDirectory>
             <filtered>true</filtered>
             <fileMode>644</fileMode>
         </file>-->
        <file>
            <source>src/repository/conf/tomcat/context.xml</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/tomcat</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <!--        <file>
                    <source>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/event-broker.xml
                    </source>
                    <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/</outputDirectory>
                    <filtered>true</filtered>
                    <fileMode>644</fileMode>
                </file>-->

        <file>
            <source>INSTALL.txt</source>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>README.txt</source>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>LICENSE.txt</source>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>release-notes.html</source>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>target/wso2carbon-core-${carbon.kernel.version}/bin/README.txt</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>target/wso2carbon-core-${carbon.kernel.version}/bin/version.txt</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <!-- Copying logging-config.xml -->
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/etc/logging-config.xml
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/etc</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <!-- Copying event-broker.xml -->
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/event-broker.xml
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <!-- Copying application-authentication.xml -->
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/identity/application-authentication.xml
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/identity
            </outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/identity/sso-idp-config.xml
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/identity
            </outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>


        <!-- Copying thrift-authentication.xml -->
        <file>
            <source>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/identity/thrift-authentication.xml
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/identity
            </outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/repository/conf/application-authenticators.xml</source>